schema_version = "1.0.0"
id = "festivity_flow"
version = "1.0.0"
name = "Flow"
tagline = "One-click procedural wavy bone chain animation"
maintainer = "festivity"
type = "add-on"
blender_version_min = "4.2.0"
license = [
  "SPDX:GPL-3.0-or-later",
]
tags = ["Animation"]
website = "https://github.com/festivities/Flow"

[permissions]
files = "Read and save custom presets to a .JSON"
